### test /
GET http://localhost:4000/

### REQUESTS
### get videoRequests
GET http://localhost:4000/video-request?sortBy=New First&topic_title=Red Dead
### get videoRequests
GET http://localhost:4000/video-request?sortBy=Top Voted First
### get videoRequests
GET http://localhost:4000/video-request?sortBy=New First
### serch video requests
GET http://localhost:4000/video-request?topic_title=SPA

### create videoRequest
POST http://localhost:4000/video-request
Content-Type: application/json

{
    "userId":"6977b455b3613242e4d44fed",
    "topic_title":"SPA", 
    "topic_details":"single page app in vanilla js"
}
### get video request by id
GET http://localhost:4000/video-request/6973a8866bbf1d53af26c4c8

### update video request by id
PATCH  http://localhost:4000/video-request/6972598234ac7f4aaa222ee5
Content-Type: application/json

{
    "target_level": "beginner"
}
### delete video request by id
DELETE  http://localhost:4000/video-request/69789a41b795bea3a5444c3b
Content-Type: application/json

{
    "userId":"6977a7ff55b9b3aef328984a"
}

### update video request vote by id
PATCH   http://localhost:4000/video-request/vote/69766ea627d6d5c3cd2a8ec4
Content-Type: application/json

{
    "vote_type":"ups"
}
### update video request status by id
PATCH   http://localhost:4000/video-request/status/6979038e612c0455c5380f96
Content-Type: application/json

{
    "status":"planned",
    "userId":"6977a7ff55b9b3aef328984a"
}
### Add video request Ref by id
PATCH   http://localhost:4000/video-request/videoRef/6979038e612c0455c5380f96
Content-Type: application/json

{
    "link": "",
    "userId":"6977a7ff55b9b3aef328984a"
}

### USERS
### sign up
POST  http://localhost:4000/user/signup 
Content-Type: application/json

{
    "author_name":"mark",
    "author_email":"markus1@mail.com"
}
### login
POST  http://localhost:4000/user/login 
Content-Type: application/json

{
    "author_name":"henryFord",
    "author_email":"GigaFord@mail.com"
}
### get all users
GET http://localhost:4000/user
### get user by id
POST http://localhost:4000/user/checkId
Content-Type: application/json

{
    "userId": "6977b455b3613242e4d44fed"
}